### PR TITLE
Screen rotation fix

### PR DESCRIPTION
**Pull request by vmobilis**
When screen rotates, activity may reset all user input or cancel waiting of generation. Making application always vertical will disable rotations.

And thanks for the program! 👍

### CODE REVIEW

**Comment by vmobilis** [comment]
@Jokimax, I saw that there was issue https://github.com/Jokimax/OpenStableDiffusion/issues/1,  but for me it seems that removing "android:screenOrientation" did not help or even made the opposite.<br>
I tested with and without it on Androids 5.1, 8 and 11: with "screenOrientation", the rotation is always portrait, with auto-rotation on or off.<br>
And when it's removed, screen rotates and restarts the activity (and cleans input or cancels generation).

**Comment by vmobilis** [comment]
Upd. Since "android:screenOrientationm" doesn't always work, maybe there is another solution:<br>
1) disable activity restart (copied from Google guide);
2) generation and image layouts will become cropped, so make buttons with regular linear weighted layouts, it works.

Result looks like this (layout is scrollable):
Open_SD_v Open_SD_h

@Jokimax, please take a look.

**Comment by Jokimax** [comment]
Thanks for the suggestion. It seems like error messages get cut off in horizontal view. I will see if there is any way to fix this.

**Comment by vmobilis** [comment]
@Jokimax, maybe this version? I didn't get how to make it with ConstraintLayout, so simply changed everything to LinearLayout. :)
It seems to work, error placeholder is now always at bottom.

I checked main/generation/result layouts in windowed mode&nbsp;– they should be usable even on small screens. 
Please take a look.

**Comment by Jokimax** [comment]
Seems to work well enough. Thanks again for all the commits. Great changes. 👍

**Pull request merged**
